name: Lint and Build

on: [push, pull_request]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-lint-build
        with:
          node-version: '20'
      